Map<int, String> authors = {
  22: 'Alana Rigal',
  24: 'Anwar Kanon',
  26: 'Darcy Fisher',
  4: 'MisterJoshW',
  5: 'FishMan',
  13: 'Harrison Bryan',
  21: 'Jeff Ruller',
  7: 'JennyBoom',
  20: 'Julia Merrill',
  15: 'Julie Nocito',
  16: 'Julie Johansson',
  27: 'Keeks Ocasio',
  1: 'Patrick Zarrelli',
  19: 'Lauren McGee',
  11: 'Santiago Rendon',
  3: 'Santino DeBlasiis',
  23: 'Shariful Haque',
  10: 'Sylvie Billings',
  25: 'Waqas	Waqas',
};
